name: "Scan and Warn Workflow"

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Pull Request Number'
        required: true

permissions: write-all

jobs:
  scan-and-warn-job:
    runs-on: ubuntu-latest
    name: A job to check for Dangerous Actions in PR
    steps:
      # Checkout the repo
      - name: CheckOut the Repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.pr_number }}
      - name: Run PR Scan and Warn Action
        uses: ZainAmjad68/pr-scan-and-warn@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          words-to-scan-for: 'destroy(), dropTable'
